import Head from "next/head";
import styles from "../styles/Home.module.css";

const Contact = () => {
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.body}>
        <h2>Connect with me </h2>
        <div>
          <ul className={styles.ul}>
            <li>
              <h3>
                <a
                  href="https://www.linkedin.com/in/nishant-540663193/"
                  className={styles.a}
                >
                  LinkedIn
                </a>
              </h3>
            </li>
            <hr />
            <li>
              <h3>
                <a href="mailto:nishantsg300@gmail.com" className={styles.a}>
                  Email
                </a>
              </h3>
            </li>
            <hr />
            <li>
              <h3>
                <a
                  href="https://drive.google.com/file/d/1QkWVCSqv4HRZqb2BeMU7WvRpXwv9ADf8/view?usp=sharing"
                  className={styles.a}
                >
                  Resume
                </a>
              </h3>
            </li>
            <hr />
            <li>
              <h3>
                <a href="tel:+918791941719" className={styles.a}>
                  Phone
                </a>
              </h3>
            </li>
            <hr />
            <li>
              <h3>
                <a href="https://github.com/nishusg" className={styles.a}>
                  Github
                </a>
              </h3>
            </li>
            <hr />

            <li>
              <h3>
                <a
                  href="https://www.hackerrank.com/nishantsg218"
                  className={styles.a}
                >
                  HackerRank
                </a>
              </h3>
            </li>
            <hr />
            <li>
              <h3>
                <a
                  href="https://www.codechef.com/users/nishusg"
                  className={styles.a}
                >
                  CodeChef
                </a>
              </h3>
            </li>
            <hr />
            <li>
              <h3>
                <a
                  href="https://www.hackerearth.com/@nishant1395"
                  className={styles.a}
                >
                  HackerEarth
                </a>
              </h3>
            </li>
          </ul>
        </div>
      </div>
    </>
  );
};
export default Contact;
