import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import pic from "../public/pics.jpg";
export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.body}>
        <div className={styles.head}>
          <h1>Nishant</h1>
          <p className={styles.edu}>
            I am Computer Science undergraduate interested in Web Development
            and Programming. I am learning lots of skill for improving my
            strategy in Software Development. I am looking opportunity for
            developing new Software.
          </p>
          <hr />
          <h2>Education</h2>
          <div className={styles.edu}>
            <h4>B.Tech in Computer Science and Information Technology</h4>
            <p>Meerut Institute of Engineering and Technology</p>
            <div>
              <p>2019-2023</p>
            </div>
          </div>
        </div>
        {/* <div>
          <Image
            src={pic}
            alt="pic"
            height="200"
            width="200"
            className={styles.img}
          />
        </div> */}
      </div>
    </>
  );
}
