import Head from "next/head";
import styles from "../styles/Home.module.css";

const Skill = () => {
  return (
    <>
      <Head>
        <title>Skill</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.body}>
        <h2>Technology Known</h2>
        <div>
          <ul className={styles.ul}>
            <li>HTML5</li>
            <hr />
            <li>CSS3</li>
            <hr />
            <li>JAVASCRIPT</li>
            <hr />
            <li>NODE.JS</li>
            <hr />
            <li>EXPRESS.JS</li>
            <hr />
            <li>MONGODB</li>
            <hr />
            <li>REACT.JS</li>
            <hr />
            <li>NEXT.JS</li>
            <hr />
            <li>JAVA</li>
            <hr />
            <li>C LANGUAGE</li>
          </ul>
        </div>
      </div>
    </>
  );
};
export default Skill;
